development:
  address: "smtp.mailgun.org"
  port: "587"
  domain: ENV['domain']
  authentication: "plain"
  user_name: ENV['user_name']
  password: ENV['password']
  enable_starttls_auto: true
# production:
#   address: "smtp.mailgun.org"
#   port: "587"
#   domain: "sandboxc39f5709e9e04e97bac91e7ac1b687df.mailgun.org"
#   authentication: "plain"
#   user_name: "postmaster@sandboxc39f5709e9e04e97bac91e7ac1b687df.mailgun.org"
#   password: "3e2f62fdff0a66207429eafdeb79ee08-71b35d7e-cf706e06"
#   enable_starttls_auto: true