import "./tailwind.scss"
import "tailwindcss/tailwind.css"
import "./discuss.scss"
import "./posts_new.scss"
import "./single_article.scss"
import "./user"
import "./marked.scss"
import "./add_discuss.scss"